# Artemis AMQP 1.0
camel.component.amqp.connection-factory=#class:org.apache.qpid.jms.JmsConnectionFactory
camel.component.amqp.connection-factory.remoteURI={{env:ARTEMIS_AMQP_URL}}
camel.component.amqp.username={{env:ARTEMIS_USER}}
camel.component.amqp.password={{env:ARTEMIS_PASSWORD}}
camel.component.amqp.connection-factory.topicPrefix=topic://

# HTTP API served by Camel Main / platform-http
camel.server.enabled=true
logging.level.org.example.fleet=INFO
